Algoritmo "Pode dirigir?"
// Disciplina   : Algotimo e Lógica de Programação]
// Professor   : Willian Szabo 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 17/03/2026
Var
// Seção de Declarações das variáveis 
idade: inteiro
cnh: logico

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 escreva("Qual é sua idade: ")
 leia(idade)
 escreva("Voce tem cnh? responda com (V/F) ")
 leia(cnh)
 
 se (idade >= 18) e (cnh) entao
    escreva("Você pode dirigir!")
 senao
      escreva("Voce não pode dirigir")
      
fimse

Fimalgoritmo