Algoritmo "Pode comprar?"
// Disciplina   : Algotimo e Lógica de Programação]
// Professor   : Willian Szabo 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 17/03/2026
Var
// Seção de Declarações das variáveis 
dinheiro: logico
cartao: logico

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 escreva("Você tem dinheiro? responda com (V/F) ")
 leia(dinheiro)
 escreva("Você tem cartão? responda com (V/F) ")
 leia(cartao)
 
 se (dinheiro) ou (cartao) entao
    escreva("Pode Comprar!")
 senao
      escreva("Não pode comprar")
      
fimse

Fimalgoritmo