Algoritmo "Nota"
// Disciplina   : Algotimo e Lógica de Programação]
// Professor   : Willian Szabo 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Guilherme
// Data atual  : 10/03/2026
Var
nota: real
Inicio
escreva("Qual sua nota: ")
leia(nota)
se (nota >= 70) entao
escreva("Voce esta aprovado")
senao
se (nota >= 40) entao
escreva("Voce esta de dependencia")
senao
escreva("voce esta reprovado")
fimse
fimse
Fimalgoritmo