Algoritmo "maior idade"
// Disciplina   : Algotimo e Lógica de Programação]
// Professor   : Willian Szabo 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Guilherme
// Data atual  : 10/03/2026
Var
// Seção de Declarações das variáveis 
idade: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Digite a sua idade: ")
leia(idade)
se (idade <= 18) entao
   escreva("Você é maior de idade")
senao
     escreva("Você é menor de idade")
fimse

Fimalgoritmo