Algoritmo "Quarto exercicio"
// Disciplina   : Algotimo e Lógica de Programação]
// Professor   : Willian Szabo 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Guilherme Szabo
// Data atual  : 24/02/2026
Var
// Seção de Declarações das variáveis 
primeiro:real
segundo:real
terceiro:real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Escreva o numero de x: ")
leia(primeiro)
escreva("Escreva o numero de y: ")
leia(segundo)
terceiro <- primeiro
primeiro <- segundo
segundo <- terceiro
escreva("o valor de x: ", primeiro, " o valor de y: ", segundo)


Fimalgoritmo