Algoritmo "Qinto exercicio"
// Disciplina   : Algotimo e Lógica de Programação]
// Professor   : Willian Szabo 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Guilherme Szabo
// Data atual  : 24/02/2026
Var
// Seção de Declarações das variáveis 
primeiro:real
segundo:real
terceiro:real
media:real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Escreva a primeira idade: ")
leia(primeiro)
escreva("Escreva a segunda idade: ")
leia(segundo)
escreva("Escreva a terceira idade: ")
leia(terceiro)
media <- (primeiro + segundo + terceiro) / 3
escreva("A média é de ", media)


Fimalgoritmo