Algoritmo "segundo exercicio"
// Disciplina   : Algotimo e Lógica de Programação]
// Professor   : Willian Szabo 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Guilherme Szabo
// Data atual  : 24/02/2026
Var
// Seção de Declarações das variáveis 
primeiro:real
segundo:real
resultado:real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Digite seu primeiro numero: ")
leia(primeiro)
escreva("Digite seu segundo numero: ")
leia(segundo)
resultado <- primeiro + segundo
escreva("O resultado da soma é: ", resultado)

Fimalgoritmo