Algoritmo "nota"
// Disciplina   : Algotimo e Lógica de Programação]
// Professor   : Willian Szabo 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Guilherme
// Data atual  : 10/03/2026
Var
// Seção de Declarações das variáveis 
nota: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Qual foi sua nota: ")
leia(nota)
se (nota >= 70) entao
   escreva("Você foi aprovado")
senao
     escreva("Você reprovou")
fimse

Fimalgoritmo