Algoritmo "terceiro exercicio"
// Disciplina   : Algotimo e Lógica de Programação]
// Professor   : Willian Szabo 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Guilherme Szabo
// Data atual  : 24/02/2026
Var
// Seção de Declarações das variáveis 
primeiro:real
segundo:real
resultado:real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Digite a base do retangulo: ")
leia(primeiro)
escreva("Digite a altura do retangulo: ")
leia(segundo)
resultado <- primeiro * segundo
escreva("A area do retangulo é: ", resultado)

Fimalgoritmo