Algoritmo "Nomes iguais"
// Disciplina   : Algotimo e Lógica de Programação]
// Professor   : Willian Szabo 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Guilherme
// Data atual  : 10/03/2026
Var
nome1: caractere
nome2: caractere
Inicio
escreva("Qual é o primeiro nome: ")
leia(nome1)
escreva("Qual é o segundo nome: ")
leia(nome2)
se (nome1 = nome2) entao
   escreva("Os dois nomes são iguais")
senao
     escreva("Os nomes não são iguais")
fimse
Fimalgoritmo